[tool.poetry]
name = "swarkn"
version = "0.1.6"
description = "swiss army knife helper functions"
authors = ["John Smith"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">= 3.9"
frozendict = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
